### ISSUE TITLE
Can't call hash.to_json without active support

### ISSUE THREAD

**Issue by msonnabaum** [karmi/retire#604]
After upgrading to 0.5.4 on a non-rails project, I noticed I was getting a NoMethodError: undefined method `as_json' for #Hash:0x007fb4d36cfc98.

This was introduced in ae3b5af45ec26536d97de03bc2e02ff574293549.

Also, the tests don't catch it, because the unit tests have active support loaded via the included models in test_helper.rb.

I can prevent the error by making the following change:

``` ruby
      def as_json(options=nil)
        hash = to_hash
        if hash.respond_to?(:with_indifferent_access)
          hash.with_indifferent_access.as_json(options)
        else
          hash.respond_to?(:as_json) ? hash.as_json(options) : hash.to_json
        end
      end
```

However, I didn't submit a PR because I feel like the tests need to be refactored to not assume activesupport is available, and I'm not sure how you want to go about doing that.

**Comment by karmi** [comment]
Good catch! Actually, _ActiveSupport_ is (unfortunately!) pulled in by _ActiveModel_, and we can't do anything about it in the current codebase, if we want to support various OxMs by `Results::Item`.

Beware of the subtle differences between `as_json` and `to_json`, a solution like you outline might be broken in subtle ways :) I think the proper solution for the time being is to just admit _ActiveSupport_ and pull it in properly. (As noted multiple times in issues, plans for a complete rewrite of the gem are in motion...)

**Comment by msonnabaum** [comment]
I think that's a totally reasonable solution for now, and then it can be solved properly when ActiveModel is decoupled later on.

**Comment by karmi** [comment]
@msonnabaum Yes, thanks! I'll have a look into admitting the _ActiveSupport_ more openly in gemspec (I'm just teriffied about version mismatches there :)

**Comment by karmi** [comment]
Admitted to ActiveSupport in gemfile, will keep it in mind for future. Thanks for the report!
