### ISSUE TITLE
will_paginate errors

### ISSUE THREAD

**Issue by kbaum** [karmi/retire#37]
Trying to create a simple search form with will paginate:

https://gist.github.com/35b576c02ce480177ec7

But i get this error:

ActionView::Template::Error (undefined method `offset' for #<Tire::Results::Collection:0x00000105314ce0>):
    1: <%= page_entries_info @email_messages %>  #-> Displaying posts 6 - 10 of 26 in total
  app/views/simple_searches/create.html.erb:1:in`_app_views_simple_searches_create_html_erb__1619823318822797195_2155602960_2692340048174035920'

Thanks!

**Comment by karmi** [comment]
Which version of will_paginate are you using? It works with `3.0.pre2` for me.

**Comment by kbaum** [comment]
I was using will_paginate (~> 3.0.pre2).  I am giving Kaminari a shot.  I saw that patch from the other issue.
https://github.com/karmi/tire/issues/14

**Comment by karmi** [comment]
Try generating the demo application as documented in the Readme. That uses will_paginate `~>3.0.pre`, and definitely works.

**Comment by kbaum** [comment]
Got it working now.  Was not passing in the page parameter to the search.

```
@email_messages = EmailMessage.search(params[:simple_search][:value], :page=>(params[:page] || 1) )
```

**Comment by kbaum** [comment]
Actually, it does not fail anymore, but when i click next or a specific page number, it does not go to the next page.

**Comment by kbaum** [comment]
Ok.. another update.  If you don't pass in :per_page, it ignores pagination all together.  So you need:

```
@email_messages = EmailMessage.search(params[:simple_search][:value], :page=>(params[:page] || 1), :per_page=>10 )
```

**Comment by karmi** [comment]
Yes, and it should definitely be optional, as in _will_paginate_. Again, the tests: https://github.com/karmi/tire/blob/master/test/integration/active_record_searchable_test.rb#L83 are really the best docs and starting point right now...
