### ISSUE TITLE
Support for decorator/presenter libraries?

### ISSUE THREAD

**Issue by mattiassvedhem** [karmi/retire#674]
It would be nice if there was an explicit way to decorate the `Tire::Results::Item` and `Tire::Results::Collection` objects. For example to easily drop in a [`Draper::Decorator`](https://github.com/drapergem/draper/blob/master/lib/draper/decorator.rb). 

I'll usually use both the plain AR model in the application, where I don't need the query capabilities of ElasticSearch, and then where I do need them I, use the Tire interface. Sharing the same Decorator between these different scenarios would be awesome. 

I know I could just set `load: true` and supposedly (haven't tried) get the AR object back, but I would like to avoid that, since one of the reasons I use ES is for performance.

Is this something you've thought about?
Thanks

**Comment by karmi** [comment]
Sounds like a very useful thing! I don't have any first-hand experience with Draper -- could you provide an example here, so we have something to discuss and play with?

(Also, note that you can easily configure your own "wrapper" for the results, instead of the default `Results::Item`.)

**Comment by mattiassvedhem** [comment]
Sure!

```
class Item < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end

class ItemDecorator < Draper::Decorator
  def full_name
    source.first_name + source.last_name
  end
end

class ItemsDecorator < Draper::CollectionDecorator
  # some grouping or other method concering multiple items.
end

item = Item.new(first_name: 'Karel', last_name: 'Minarik')
decorated = ItemDecorator.new(item)
decorated.full_name = 'Karel Minarik'

# OR
items = Item.all
decorated_collection = ItemsDecorator.new(items.all) # Decorates each of them with ItemDecorator
decorated_collection.first.class
=> ItemDecorator
```

I guess the sharing of an item decorator could be achieved this way:

```
Tire.configuration.wrapper = Item
results = Item.search(first_name: 'Karel') 
results.each do |item|
  decorated = item.decorate # Draper provides this method by mixin in a module, Draper::Decoratable, in the model.
  decorated.full_name
  => 'Karel Minarik'
end
```

However with that approach I couldn't easily keep the Collection and have my decorated objects via `#results`.  

What I'm after would be a simpler way to decorate both the Item and the Collection.
I don't necessarily want to replace either `Tire::Results::Collection` or `Tire::Results::Item` but I would like to be able to wrap a class around them and retain the methods of Collection and Item.

For example by adding `delegate_all` to the decorator I could delegate all the methods called on it to `Tire::Results::Item` or `Tire::Results::Collection` and just benefit from having extra methods available for the view logic.

```
items = Item.search(first_name: 'Karel')
items.class
=> ItemsDecorator

items.source
=> Tire::Results::Collection

items.first.class
=> ItemDecorator

items.first.source
=> Tire::Results::Item

items.first.full_name
=> 'Karel Minarik'
```

**Comment by mattiassvedhem** [comment]
I'll do some experiments and see what I can come up with.

**Comment by mattiassvedhem** [comment]
Turns out this already works pretty good! Although there is some things that does not work as expected, I'll investigate them further and figure out if it's an issue with draper or tire.

**Comment by mattiassvedhem** [comment]
The only thing that doesn't work is the automatic delegation to the source object, this doesn't work since Draper's AutomaticDelegation implements a `method_missing` which checks if the source object responds to the method before delegating it.

It's not really that big of a problem, as we can just delegate all the methods manually, but I guess it could be solved by switching out `Tire::Results::Item` to an object that actually defines the hash keys as methods dynamically and not relying on `method_missing` — But I guess there's a reason for not doing so?

Edit: Although I just saw [this](https://github.com/karmi/tire/blob/master/lib/tire/results/item.rb#L29), which means that it should work as is..

```
def respond_to?(method_name, include_private = false)
  @attributes.has_key?(method_name.to_sym) || super
end
```

but:

```
items = Item.search(first_name: 'Karel')
items.first
=> <Item (Item) id: "4f99f0eea2b279ec3d000006", first_name: "Karel", , _score: nil, _type: "item", _index: "items", _version: nil>
items.first.respond_to?(:first_name)
=> false # Shouldn't this be true?
items.first.first_name
```

edit2: Turns out I tested on 0.4.x, works correctly in 0.5.x.

**Comment by karmi** [comment]
Mattias, thanks for all the digging! It was my initial impression that it should be achievable easily, so it's great that it works out of the box.

So, just to check:

1/ You decorate the `Item` instances just by providing a different `:wrapper` class? (You've used `Item` which is a bit confusing to me :)
2/ You decorate the search results `Collection` by passing it to your decorator? (ie. `MyResultsDecorator.new(search.results.to_a)`)

> an object that actually defines the hash keys as methods dynamically and not relying on method_missing

As you've discovered, there's been the `respond_to?` added inbetween, so it should work. The case you have is weird, notice there's a [test](https://github.com/karmi/tire/blob/master/test/unit/results_item_test.rb#L68-L71) basically doing that... I'll check it once again.

Lastly, the reason for `method_missing` is (as usual) conveniece/laziness -- given how dynamic Elasticsearch is, many different documents come out of a simple `Tire.search('indexA', 'indexB' ,...)` -- I guess it wouldn't be practical to define accessors for all of them dynamically. Maybe it would even impact performance significantly.

For future versions, I'd like to research all the “objectified Hash” libraries once again -- in the beginning, I wanted full control in this part and not used something like [_Hashie_](https://github.com/intridea/hashie) or [_Hashr_](https://github.com/svenfuchs/hashr). (Notice, though, that the `Model::Persistence` support uses Hashr to cast Hashes.)

**Comment by mattiassvedhem** [comment]
No, we don't really need to switch out the wrapper, that was just an initial thought on how to do it.

### 1. We could define just a ordinary `Draper::Decorator`

```
ItemDecorator < Draper::Decorator
  delegate_all # or just the methods we want to pass on to the Tire::Results::Item instance. 
  # ... and put some methods here
  def name
    source.first_name + source.last_name
  end
end
```

We can then use it like this

```
items = Item.search(query: 'something')
decorated_items = ItemDecorator.decorate_collection(items)
```

That would give us an instance of `Draper::CollectionDecorator` which is the default collection decorator in draper.
So we could then do:

```
decorated_items.first.name
=> 'The name'
```

However, what we cannot do with this approach is to get to any facets or other methods defined on the `Tire::Results::Collection` object.

```
decorated_items.facets
=> NoMethodError: undefined method `facets' for #<Draper::CollectionDecorator:0x007f836d9888f0>
```

That's because the default collection decorator does not automatically delegate those methods to the source `Tire::Search::Collection` instance. So if we don't need to access those properties, we are fine with this method. 

Otherwise we'll need to do it like this:

### 2. Define a `Draper::CollectionDecorator`

```
ItemsDecorator < Draper::CollectionDecorator
  # There's no delegate_all here so we'll need to delegate all methods we want to pass on to the Tire::Search::Collection
  delegate :facets
end
```

We can now use this collection decorator directly to decorate both the collection and the items. Draper will automatically look for a decorator named `ItemDecorator`, loop through our hits and wrap them with it.

```
items = Item.search(query: 'something')
decorated_items = ItemsDecorator.new(items)

decorated_items.facets
=> { hash with the facets }

decorated_items.first.name
=> 'The name'

# We also still have the methods from Tire::Results::Item at arms length 
since we used delegate_all in our ItemDecorator.
decorated_items.first._score
=> '0.30685282'
```

Now we can reuse our view models between Tire and ActiveRecord/Mongoid, as long as they adhere to the same interface (attributes).

If you want I can write a wiki entry with a detailed explanation on how to use Tire with Draper.

Ah, I see, that makes sense, it does work with the 0.5.x versions, I accidently used an older version of Tire which didn't have the modified respond_to?.

**Comment by karmi** [comment]
Mattias, that's terriffic new. I'm glad it works like this, because augmenting the result items/collection is something users often seem to struggle with.

>  If you want I can write a wiki entry with a detailed explanation on how to use Tire with Draper.

I was about to ask you just that :) That would be really, really great!

**Comment by mattiassvedhem** [comment]
Yeah I'm glad it worked too! We'll start using it in our applications.

I added a wiki entry [here](https://github.com/karmi/tire/wiki/Using-Tire-with-Draper).

Let me know if there's something that needs further explanation, I think it's pretty straight forward though!

**Comment by karmi** [comment]
That is an awesome writeup, thank you!
